---
- hosts: influxdb
  become: true
  vars:
    hostname: influxdb.galaxyproject.eu
  vars_files:
    - "secret_group_vars/all.yml"
  pre_tasks:
    - name: Set default version of Python
      alternatives:
        name: python
        path: /usr/bin/python3
    - name: Install docker pip package
      ansible.builtin.pip:
        name: docker
    - name: Set docker_users (Docker role)
      set_fact:
        docker_users: "centos"
    - name: Configure SELinux
      ansible.posix.seboolean:
        name: "{{ item }}"
        state: true
        persistent: true
      loop:
        - httpd_can_network_connect
    - name: Disable firewalld service
      ansible.builtin.service:
        name: firewalld
        enabled: false
        state: stopped
  collections:
    - devsec.hardening
  roles:
    ## Starting configuration of the operating system
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_hostname: true
        enable_powertools: true        # geerlingguy.repo-epel role doesn't enable PowerTools repository
        enable_remap_user: true
        enable_create_user: true
#    - geerlingguy.repo-epel     # Install EPEL repository
#    - usegalaxy-eu.autoupdates  # keep all of our packages up to date
#    - influxdata.chrony         # Keep our time in sync.
#    - usegalaxy-eu.dynmotd
#    - hxr.monitor-email
#    # Applications
#    - geerlingguy.docker
#    - galaxyproject.nginx
    - usegalaxy_eu.influxdbserver
    - dj-wasabi.telegraf
    # hardening
    - os_hardening
    - ssh_hardening
