---
- name: Install and configure rustus
  hosts: upload
  become: true
  become_user: root
  vars_files:
    - group_vars/all.yml
    - secret_group_vars/sentry.yml
    - mounts/mountpoints.yml
    - mounts/dest/all.yml
  pre_tasks:
    - ansible.posix.firewalld:
        zone: public
        port: 1080-1081/tcp
        permanent: true
        state: enabled

  roles:
    - role: usegalaxy_eu.handy.os_setup
      vars:
        enable_remap_user: true
        enable_create_user: true
        enable_kernel_5: true
        enable_install_software: true
    - influxdata.chrony
    ## Filesystems
    - usegalaxy-eu.autofs     # Setup the mount points which will be needed later

    - usegalaxy_eu.rustus
