---
- name: Install dependencies
  ansible.builtin.package:
    name: jq
    state: present

- name: "Deploy remove-orphan-condor-jobs script"
  ansible.builtin.copy:
    src: remove-orphan-condor-jobs
    dest: "{{ remove_orphan_jobs_bin }}"
    owner: root
    group: root
    mode: 0755

- name: Create logfile
  ansible.builtin.file:
    state: touch
    path: "{{ remove_orphan_jobs_log }}"
    mode: 0664
    owner: "{{ galaxy_user.name }}"
    group: "{{ galaxy_group.name }}"

- name: Setup logrotate
  ansible.builtin.copy:
    content: |
      {{ remove_orphan_jobs_log }}
      {
          rotate 6
          daily
          missingok
          dateext
          copytruncate
          notifempty
          compress
      }
    dest: /etc/logrotate.d/remove-orphan-condor-jobs
    mode: 0664
    owner: root
    group: root

- name: Add to cron
  ansible.builtin.cron:
    name: "Remove jobs that are running in condor but unknown to galaxy"
    day: "*"
    hour: "*/1"
    minute: "0"
    user: "{{ galaxy_user.name }}"
    job: "{{ remove_orphan_jobs_bin }} >> {{ remove_orphan_jobs_log }} 2>&1"

