# Configure nodes in the secondary HTCondor cluster.
#
# Nodes in the secondary HTCondor cluster belong both to the
# "htcondor-secondary" (with group priority > 1) and "htcondor" groups. They
# thus inherit variables from the latter.
---
htcondor_server: "build.galaxyproject.eu"
htcondor_port: 9628
